### PR TITLE
Bump Quarkus to 2.1.0.Final

### PR DESCRIPTION
**Pull request by pilhuhn**

### CODE REVIEW

**Comment by gwenneg** [comment]
Do the non-application API (`/health` and friends) still work after that bump without changing the configuration?

**Comment by gwenneg** [comment]
```
2021-07-29T09:55:11.5374768Z 2021-07-29 09:55:09,938 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.redirect-to-non-application-root-path" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

**Comment by bennetelli** [comment]
I would expect to have a failing test if something isn't working. Will take a look at it the next minutes.

**Comment by pilhuhn** [comment]
@bennetelli we don't test triggering health checks or retrieving metrics.

**Comment by gwenneg** [comment]
Fixed in #81.

**Pull request merged**
