### PR TITLE
Remove clowder dependency

### PR DESCRIPTION
**Pull request by g-duval**

### CODE REVIEW

**Comment by josejulio** [comment]
We are not going to use clowder anymore? or is included in any other way?

Asking because I see this one https://github.com/RedHatInsights/notifications-gw/blob/main/src/main/resources/application.properties#L15

**Comment by g-duval** [comment]
@josejulio , we have a "java.lang.OutOfMemoryError: Java heap space" error when we try to bump Quarkus version >  3.4.3 on stage.
According logs, Stage uses com.red.clo.not.clo.KafkaSaslInitializer, but ephemeral does not. 
I'm trying to understand why.

**Comment by g-duval** [comment]
just testing

**Comment by josejulio** [comment]
oh ok ! thanks!

**Pull request closed without merging**
