### PR TITLE
add kafka topic to clowdapp

### PR DESCRIPTION
**Pull request by lahavyuv86**

### CODE REVIEW

**Comment by theute** [comment]
There is something I don't quite grasp here.
Sounds like we're declaring Kafka topic in all pods (and ask for creation) ?
Aren't we supposed to have a single ClowdApp for all pods (and not 1 per pod) and then a single Kafka topic declaration ?

**Comment by theute** [comment]
The [doc says](https://redhatinsights.github.io/clowder/api_reference.html#k8s-api-cloud-redhat-com-clowder-v2-apis-cloud-redhat-com-v1alpha1-databaseconfig):

> ClowdAppSpec is the main specification for a single Clowder Application it defines n pods along with dependencies that are shared between them.

> A list of Kafka topics that will be created and made available to all the pods listed in the ClowdApp.

I'm really not familiar but it seems odd to me to ask for topic creation in all pods (potentially with different replicas and partitions values ?)

**Comment by pilhuhn** [comment]
We are currently facing an issue where clowder is not injecting the topic (and brokers) into /cdapp/cdappconfig.yaml for the -gw.
We should perhaps just try it out and see if we get a different topic here than in -backend or if they are the same.

**Comment by lahavyuv86** [comment]
I agree it seems odd, but now we're in a stage that the cdappconfig.json on notifications-gw pod doesn't have the specifications for the kafka topic which results with connection fail errors.

**Comment by theute** [comment]
I know about the issue, but reading the doc it seems that we should only have 1 Clowder app file (I guess in any of the repo) and not one per pod, and then declare it ones (and then I guess injected in both), I could be wrong

**Pull request merged**
