### PR TITLE
Allow to by-pass by event-types as well (bundle:app:event_type)

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]
LGTM

**Comment by gwenneg** [comment]
Please wait a bit before merging this, I need to discuss the previous PR first.

**Comment by gwenneg** [comment]
I'm closing this PR because it won't be needed. @g-duval will open another PR to restrict the org ID validation to OCM events only.

**Comment by g-duval** [comment]
@josejulio https://github.com/RedHatInsights/notifications-gw/pull/390 should solve your issue

**Pull request closed without merging**
